
// HTTPDNS_LOG_TRACE, HTTPDNS_LOG_DEBUG, HTTPDNS_LOG_INFO, HTTPDNS_LOG_WARN, HTTPDNS_LOG_ERROR, HTTPDNS_LOG_FATAL
#define HTTPDNS_LOG_LEVEL       HTTPDNS_LOG_INFO
#define HTTPDNS_LOG_FILE_PATH           /tmp/httpdns.log
#define HTTPDNS_REGION          cn
#define HTTPDNS_RETRY_TIMES     1
